apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "node-app-test"
  annotations:
    github.com/project-slug: AnsonYe/node-app-test-create-from-backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
